source 'https://rubygems.org'

gem 'cucumber'
gem 'data_magic'
gem 'fig_newton'
gem 'page-object'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'rspec-expectations'
gem 'watir'
gem 'watir-scroll'
gem 'watir-webdriver'
